---

# This is the composition of a few Docker containers running the bare minimum
# of Cloudera Hadoop fundamental services such as Hadoop HDFS and YARN.
# There's also a Kerberos KDC - Key Distribution Centre in the mix.
#

version: "3.7"


volumes:
  shared:


networks:
  docker-net:
    name: "docker.net"


services:
  kdc:
    image: "$registry/$repository/kdc:$image_version"
    hostname: "kdc.docker.net"
    networks:
      - docker-net
    ports:
      - "4088:4088"
      - "4088:4088/udp"
    volumes:
      - "shared:/shared"


  namenode:
    image: "$registry/$repository/hadoop-hdfs/namenode:$image_version"
    environment:
      HADOOP_AUTHENTICATION: "$hadoop_auth"
      SASL_PROTECTION: "$sasl_protection"
      TLS_ENCRYPTION: "$tls_encryption"
    hostname: "namenode.docker.net"
    networks:
      - docker-net
    ports:
      - "50070:50070" # http
      - "8020:8020"   # protobuf
      #- "5051:5051"  # jvm-debug
    volumes:
      - "shared:/shared"
    depends_on:
      - kdc


  datanode1:
    image: "$registry/$repository/hadoop-hdfs/datanode:$image_version"
    environment:
      HADOOP_AUTHENTICATION: "$hadoop_auth"
      SASL_PROTECTION: "$sasl_protection"
      TLS_ENCRYPTION: "$tls_encryption"
    privileged: true
    hostname: "datanode1.docker.net"
    networks:
      - docker-net
    ports:
      - "50020:50020" # protbuf (ipc)
      - "50010:50010" # protbuf (data transfer)
      - "1004:1004"   # protbuf (data transfer)
      - "50075:50075" # http
      - "1006:1006"   # http
      #- "5052:5052"  # jvm-debug
    volumes:
      - "shared:/shared"
    depends_on:
      - namenode


  jobhistory:
    image: "$registry/$repository/hadoop-mapred/jobhistory:$image_version"
    environment:
      HADOOP_AUTHENTICATION: "$hadoop_auth"
      SASL_PROTECTION: "$sasl_protection"
      TLS_ENCRYPTION: "$tls_encryption"
    hostname: "jobhistory.docker.net"
    networks:
      - docker-net
    ports:
      - "19888:19888" # http      (yarn-ui)
      - "10020:10020" # protobuf
      #- "5053:5053"  # jvm-debug
    volumes:
      - "shared:/shared"
    depends_on:
      - namenode


  resourcemanager:
    image: "$registry/$repository/hadoop-yarn/resourcemanager:$image_version"
    environment:
      HADOOP_AUTHENTICATION: "$hadoop_auth"
      SASL_PROTECTION: "$sasl_protection"
      TLS_ENCRYPTION: "$tls_encryption"
    hostname: "resourcemanager.docker.net"
    networks:
      - docker-net
    ports:
      - "8088:8088"   # http      (yarn-ui)
      - "8032:8032"   # protobuf
      - "8030:8030"   # protobuf
      #- "5054:5054"  # jvm-debug
    volumes:
      - "shared:/shared"
    depends_on:
      - namenode
      - jobhistory


  nodemanager1:
    image: "$registry/$repository/hadoop-yarn/nodemanager:$image_version"
    environment:
      HADOOP_AUTHENTICATION: "$hadoop_auth"
      SASL_PROTECTION: "$sasl_protection"
      TLS_ENCRYPTION: "$tls_encryption"
    hostname: "nodemanager1.docker.net"
    networks:
      - docker-net
    ports:
      - "8041:8041"   # protobuf
      - "8042:8042"   # http     (yarn-ui)
      - "8043:8043"   # protobuf (map-reduce-AM)
      - "4041:4040"   # http     (spark-ui)
      #- "5055:5055"  # jvm-debug
    volumes:
      - "shared:/shared"
    depends_on:
      - namenode
      - jobhistory
      - resourcemanager


  mysql:
    image: "mysql:5.5"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "hive"
      MYSQL_PASSWORD: "hive"
      MYSQL_DATABASE: "hive"
    hostname: "mysql.docker.net"
    networks:
      - docker-net
    ports:
      - "3306:3306"


  hivemetastore:
    image: "$registry/$repository/hive/metastore:$image_version"
    hostname: "hivemetastore.docker.net"
    networks:
      - docker-net
    ports:
      - "9083:9083"   # thrift
    volumes:
      - "shared:/shared"
    depends_on:
      - mysql


  hiveserver2:
    image: "$registry/$repository/hive/server2:$image_version"
    hostname: "hiveserver2.docker.net"
    environment:
      HADOOP_AUTHENTICATION: "$hadoop_auth"
      SASL_PROTECTION: "$sasl_protection"
      TLS_ENCRYPTION: "$tls_encryption"
    networks:
      - docker-net
    ports:
      - "10000:10000" # jdbc
      #- "5056:5056"  # jvm-debug
    volumes:
      - "shared:/shared"
    depends_on:
      - namenode
      - resourcemanager
      - hivemetastore
